---
# tasks file for common

- name: Installation des logiciels communs
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - vim
    - tree
    - git
    - htop
    # tooling docker
    - docker.io
    - python-docker
    # tooling mysql
    - mysql-client
    - python-mysqldb
